"""Значения по умолчанию для автоисправления опечаток ASR.

Дублируются в ``config.example.env`` как
``CORRECTION_MIN_WORD_LENGTH``, ``CORRECTION_MIN_SIMILARITY``,
``CORRECTION_MAX_CANDIDATES``.
"""

DEFAULT_CORRECTION_MIN_WORD_LENGTH = 6
DEFAULT_CORRECTION_MIN_SIMILARITY = 0.85
DEFAULT_CORRECTION_MAX_CANDIDATES = 8000
